-- Campus Maintenance Service Operations Optimizer
-- Schema for the 4 core tables + auto-generated algorithm_runs log.
-- Target: SQLite (adjust AUTOINCREMENT / types if using MySQL or PostgreSQL).

CREATE TABLE IF NOT EXISTS locations (
    location_id      TEXT PRIMARY KEY,
    name              TEXT NOT NULL,
    area              TEXT NOT NULL,
    location_type     TEXT NOT NULL,
    x_coord           REAL NOT NULL,
    y_coord           REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS roads (
    road_id           TEXT PRIMARY KEY,
    from_location_id  TEXT NOT NULL REFERENCES locations(location_id),
    to_location_id    TEXT NOT NULL REFERENCES locations(location_id),
    distance_km       REAL NOT NULL,
    travel_time_min   REAL NOT NULL,
    condition_weight  REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS service_requests (
    request_id               TEXT PRIMARY KEY,
    source_location_id       TEXT NOT NULL REFERENCES locations(location_id),
    destination_location_id  TEXT NOT NULL REFERENCES locations(location_id),
    category                 TEXT NOT NULL,
    urgency                  TEXT NOT NULL CHECK (urgency IN ('CRITICAL','HIGH','MEDIUM','LOW')),
    time_submitted            TEXT NOT NULL,
    deadline                  TEXT NOT NULL,
    status                    TEXT NOT NULL CHECK (status IN ('NEW','IN_PROGRESS','DONE'))
);

CREATE TABLE IF NOT EXISTS resources (
    resource_id           TEXT PRIMARY KEY,
    resource_type         TEXT NOT NULL,
    home_location_id      TEXT NOT NULL REFERENCES locations(location_id),
    capacity              INTEGER NOT NULL,
    availability_status   TEXT NOT NULL CHECK (availability_status IN ('AVAILABLE','BUSY','OFF_DUTY'))
);

-- Auto-generated by the Performance Lab menu (Section 6) — not seeded from CSV.
CREATE TABLE IF NOT EXISTS algorithm_runs (
    run_id           INTEGER PRIMARY KEY AUTOINCREMENT,
    algorithm_name   TEXT NOT NULL,
    input_size       INTEGER NOT NULL,
    time_ns          INTEGER NOT NULL,
    memory_kb         INTEGER NOT NULL,
    date_run          TEXT NOT NULL
);
